
/*******************************************************************************
   Chinook Database - Version 1.4.5
   Script: Chinook_MySql.sql
   Description: Creates and populates the Chinook database.
   DB Server: MySql
   Author: Luis Rocha
   License: https://github.com/lerocha/chinook-database/blob/master/LICENSE.md
********************************************************************************/

/*******************************************************************************
  WARNING: This file was generated by a tool and changes to this file
           will be lost when this file is regenerated.
********************************************************************************/

/*******************************************************************************
   Drop database if it exists
********************************************************************************/
--MODIFIED-- DROP DATABASE IF EXISTS Chinook CASCADE;


/*******************************************************************************
   Create database
********************************************************************************/
--MODIFIED-- CREATE DATABASE Chinook;


USE Chinook;


/*******************************************************************************
   Create Tables
********************************************************************************/

--MODIFIED-- CREATE TABLE Album
--MODIFIED-- (
--MODIFIED--     AlbumId INT NOT NULL,
--MODIFIED--     Title VARCHAR(160) NOT NULL,
--MODIFIED--     ArtistId INT NOT NULL,
--MODIFIED--     CONSTRAINT PK_Album PRIMARY KEY  (AlbumId)
--MODIFIED-- );
--MODIFIED-- 
--MODIFIED-- CREATE TABLE Artist
--MODIFIED-- (
--MODIFIED--     ArtistId INT NOT NULL,
--MODIFIED--     Name VARCHAR(120),
--MODIFIED--     CONSTRAINT PK_Artist PRIMARY KEY  (ArtistId)
--MODIFIED-- );
--MODIFIED-- 
--MODIFIED-- CREATE TABLE Customer
--MODIFIED-- (
--MODIFIED--     CustomerId INT NOT NULL,
--MODIFIED--     FirstName VARCHAR(40) NOT NULL,
--MODIFIED--     LastName VARCHAR(20) NOT NULL,
--MODIFIED--     Company VARCHAR(80),
--MODIFIED--     Address VARCHAR(70),
--MODIFIED--     City VARCHAR(40),
--MODIFIED--     State VARCHAR(40),
--MODIFIED--     Country VARCHAR(40),
--MODIFIED--     PostalCode VARCHAR(10),
--MODIFIED--     Phone VARCHAR(24),
--MODIFIED--     Fax VARCHAR(24),
--MODIFIED--     Email VARCHAR(60) NOT NULL,
--MODIFIED--     SupportRepId INT,
--MODIFIED--     CONSTRAINT PK_Customer PRIMARY KEY  (CustomerId)
--MODIFIED-- );
--MODIFIED-- 
--MODIFIED-- CREATE TABLE Employee
--MODIFIED-- (
--MODIFIED--     EmployeeId INT NOT NULL,
--MODIFIED--     LastName VARCHAR(20) NOT NULL,
--MODIFIED--     FirstName VARCHAR(20) NOT NULL,
--MODIFIED--     Title VARCHAR(30),
--MODIFIED--     ReportsTo INT,
--MODIFIED--     BirthDate DATE /*MODIFIED*/,
--MODIFIED--     HireDate DATE /*MODIFIED*/,
--MODIFIED--     Address VARCHAR(70),
--MODIFIED--     City VARCHAR(40),
--MODIFIED--     State VARCHAR(40),
--MODIFIED--     Country VARCHAR(40),
--MODIFIED--     PostalCode VARCHAR(10),
--MODIFIED--     Phone VARCHAR(24),
--MODIFIED--     Fax VARCHAR(24),
--MODIFIED--     Email VARCHAR(60),
--MODIFIED--     CONSTRAINT PK_Employee PRIMARY KEY  (EmployeeId)
--MODIFIED-- );
--MODIFIED-- 
--MODIFIED-- CREATE TABLE Genre
--MODIFIED-- (
--MODIFIED--     GenreId INT NOT NULL,
--MODIFIED--     Name VARCHAR(120),
--MODIFIED--     CONSTRAINT PK_Genre PRIMARY KEY  (GenreId)
--MODIFIED-- );
--MODIFIED-- 
--MODIFIED-- CREATE TABLE Invoice
--MODIFIED-- (
--MODIFIED--     InvoiceId INT NOT NULL,
--MODIFIED--     CustomerId INT NOT NULL,
--MODIFIED--     InvoiceDate DATE /*MODIFIED*/ NOT NULL,
--MODIFIED--     BillingAddress VARCHAR(70),
--MODIFIED--     BillingCity VARCHAR(40),
--MODIFIED--     BillingState VARCHAR(40),
--MODIFIED--     BillingCountry VARCHAR(40),
--MODIFIED--     BillingPostalCode VARCHAR(10),
--MODIFIED--     Total NUMERIC(10,2) NOT NULL,
--MODIFIED--     CONSTRAINT PK_Invoice PRIMARY KEY  (InvoiceId)
--MODIFIED-- );
--MODIFIED-- 
--MODIFIED-- CREATE TABLE InvoiceLine
--MODIFIED-- (
--MODIFIED--     InvoiceLineId INT NOT NULL,
--MODIFIED--     InvoiceId INT NOT NULL,
--MODIFIED--     TrackId INT NOT NULL,
--MODIFIED--     UnitPrice NUMERIC(10,2) NOT NULL,
--MODIFIED--     Quantity INT NOT NULL,
--MODIFIED--     CONSTRAINT PK_InvoiceLine PRIMARY KEY  (InvoiceLineId)
--MODIFIED-- );
--MODIFIED-- 
--MODIFIED-- CREATE TABLE MediaType
--MODIFIED-- (
--MODIFIED--     MediaTypeId INT NOT NULL,
--MODIFIED--     Name VARCHAR(120),
--MODIFIED--     CONSTRAINT PK_MediaType PRIMARY KEY  (MediaTypeId)
--MODIFIED-- );
--MODIFIED-- 
--MODIFIED-- CREATE TABLE Playlist
--MODIFIED-- (
--MODIFIED--     PlaylistId INT NOT NULL,
--MODIFIED--     Name VARCHAR(120),
--MODIFIED--     CONSTRAINT PK_Playlist PRIMARY KEY  (PlaylistId)
--MODIFIED-- );
--MODIFIED-- 
--MODIFIED-- CREATE TABLE PlaylistTrack
--MODIFIED-- (
--MODIFIED--     PlaylistId INT NOT NULL,
--MODIFIED--     TrackId INT NOT NULL,
--MODIFIED--     CONSTRAINT PK_PlaylistTrack PRIMARY KEY  (PlaylistId, TrackId)
--MODIFIED-- );
--MODIFIED-- 
--MODIFIED-- CREATE TABLE Track
--MODIFIED-- (
--MODIFIED--     TrackId INT NOT NULL,
--MODIFIED--     Name VARCHAR(200) NOT NULL,
--MODIFIED--     AlbumId INT,
--MODIFIED--     MediaTypeId INT NOT NULL,
--MODIFIED--     GenreId INT,
--MODIFIED--     Composer VARCHAR(220),
--MODIFIED--     Milliseconds INT NOT NULL,
--MODIFIED--     Bytes INT,
--MODIFIED--     UnitPrice NUMERIC(10,2) NOT NULL,
--MODIFIED--     CONSTRAINT PK_Track PRIMARY KEY  (TrackId)
--MODIFIED-- );


/*******************************************************************************
   Create Primary Key Unique Indexes
********************************************************************************/

/*******************************************************************************
   Create Foreign Keys
********************************************************************************/

ALTER TABLE Album ADD CONSTRAINT FK_AlbumArtistId
    FOREIGN KEY (ArtistId) REFERENCES Artist (ArtistId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX IFK_AlbumArtistId ON Album (ArtistId);

ALTER TABLE Customer ADD CONSTRAINT FK_CustomerSupportRepId
    FOREIGN KEY (SupportRepId) REFERENCES Employee (EmployeeId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX IFK_CustomerSupportRepId ON Customer (SupportRepId);

ALTER TABLE Employee ADD CONSTRAINT FK_EmployeeReportsTo
    FOREIGN KEY (ReportsTo) REFERENCES Employee (EmployeeId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX IFK_EmployeeReportsTo ON Employee (ReportsTo);

ALTER TABLE Invoice ADD CONSTRAINT FK_InvoiceCustomerId
    FOREIGN KEY (CustomerId) REFERENCES Customer (CustomerId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX IFK_InvoiceCustomerId ON Invoice (CustomerId);

ALTER TABLE InvoiceLine ADD CONSTRAINT FK_InvoiceLineInvoiceId
    FOREIGN KEY (InvoiceId) REFERENCES Invoice (InvoiceId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX IFK_InvoiceLineInvoiceId ON InvoiceLine (InvoiceId);

ALTER TABLE InvoiceLine ADD CONSTRAINT FK_InvoiceLineTrackId
    FOREIGN KEY (TrackId) REFERENCES Track (TrackId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX IFK_InvoiceLineTrackId ON InvoiceLine (TrackId);

ALTER TABLE PlaylistTrack ADD CONSTRAINT FK_PlaylistTrackPlaylistId
    FOREIGN KEY (PlaylistId) REFERENCES Playlist (PlaylistId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX IFK_PlaylistTrackPlaylistId ON PlaylistTrack (PlaylistId);

ALTER TABLE PlaylistTrack ADD CONSTRAINT FK_PlaylistTrackTrackId
    FOREIGN KEY (TrackId) REFERENCES Track (TrackId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX IFK_PlaylistTrackTrackId ON PlaylistTrack (TrackId);

ALTER TABLE Track ADD CONSTRAINT FK_TrackAlbumId
    FOREIGN KEY (AlbumId) REFERENCES Album (AlbumId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX IFK_TrackAlbumId ON Track (AlbumId);

ALTER TABLE Track ADD CONSTRAINT FK_TrackGenreId
    FOREIGN KEY (GenreId) REFERENCES Genre (GenreId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX IFK_TrackGenreId ON Track (GenreId);

ALTER TABLE Track ADD CONSTRAINT FK_TrackMediaTypeId
    FOREIGN KEY (MediaTypeId) REFERENCES MediaType (MediaTypeId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX IFK_TrackMediaTypeId ON Track (MediaTypeId);


/*******************************************************************************
   Populate Tables
********************************************************************************/

/* DELETED LINES */
